	float z_t(z_t) ;
	float z_t_150m(z_t_150m) ;
	float z_w(z_w) ;
	float z_w_top(z_w_top) ;
	float z_w_bot(z_w_bot) ;
	float lat_aux_grid(lat_aux_grid) ;
	float moc_z(moc_z) ;
	float dz(z_t) ;
	float dzw(z_w) ;
	float UVEL(time, z_t, nlat, nlon) ;
	float VVEL(time, z_t, nlat, nlon) ;
	float TEMP(time, z_t, nlat, nlon) ;
	float dTEMP_POS_2D(time, nlat, nlon) ;
	float dTEMP_NEG_2D(time, nlat, nlon) ;
	float SALT(time, z_t, nlat, nlon) ;
	float SSS2(time, nlat, nlon) ;
	float RHO(time, z_t, nlat, nlon) ;
	float RHO_VINT(time, nlat, nlon) ;
	float RESID_T(time, nlat, nlon) ;
	float RESID_S(time, nlat, nlon) ;
	float SU(time, nlat, nlon) ;
	float SV(time, nlat, nlon) ;
	float SSH(time, nlat, nlon) ;
	float SSH2(time, nlat, nlon) ;
	float SHF(time, nlat, nlon) ;
	float SHF_QSW(time, nlat, nlon) ;
	float SFWF(time, nlat, nlon) ;
	float SFWF_WRST(time, nlat, nlon) ;
	float TAUX(time, nlat, nlon) ;
	float TAUX2(time, nlat, nlon) ;
	float TAUY(time, nlat, nlon) ;
	float TAUY2(time, nlat, nlon) ;
	float FW(time, nlat, nlon) ;
	float TFW_T(time, nlat, nlon) ;
	float TFW_S(time, nlat, nlon) ;
	float EVAP_F(time, nlat, nlon) ;
	float PREC_F(time, nlat, nlon) ;
	float SNOW_F(time, nlat, nlon) ;
	float MELT_F(time, nlat, nlon) ;
	float ROFF_F(time, nlat, nlon) ;
	float IOFF_F(time, nlat, nlon) ;
	float SALT_F(time, nlat, nlon) ;
	float SENH_F(time, nlat, nlon) ;
	float LWUP_F(time, nlat, nlon) ;
	float LWDN_F(time, nlat, nlon) ;
	float MELTH_F(time, nlat, nlon) ;
	float IFRAC(time, nlat, nlon) ;
	float FRACR_BIN_01(time, nlat, nlon) ;
	float QSW_BIN_01(time, nlat, nlon) ;
	float FRACR_BIN_02(time, nlat, nlon) ;
	float QSW_BIN_02(time, nlat, nlon) ;
	float FRACR_BIN_03(time, nlat, nlon) ;
	float QSW_BIN_03(time, nlat, nlon) ;
	float FRACR_BIN_04(time, nlat, nlon) ;
	float QSW_BIN_04(time, nlat, nlon) ;
	float FRACR_BIN_05(time, nlat, nlon) ;
	float QSW_BIN_05(time, nlat, nlon) ;
	float FRACR_BIN_06(time, nlat, nlon) ;
	float QSW_BIN_06(time, nlat, nlon) ;
	float zsatcalc(time, nlat, nlon) ;
	float zsatarag(time, nlat, nlon) ;
	float photoC_TOT_zint_100m(time, nlat, nlon) ;
	float photoC_NO3_TOT_zint_100m(time, nlat, nlon) ;
	float DOC_prod_zint_100m(time, nlat, nlon) ;
	float DOC_remin_zint_100m(time, nlat, nlon) ;
	float DOCr_remin_zint_100m(time, nlat, nlon) ;
	float calcToSed_ALT_CO2(time, nlat, nlon) ;
	float sp_N_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float sp_P_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float sp_Fe_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float sp_light_lim_surf(time, nlat, nlon) ;
	float sp_light_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float photoC_sp_zint_100m(time, nlat, nlon) ;
	float graze_sp_zint_100m(time, nlat, nlon) ;
	float graze_sp_poc_zint_100m(time, nlat, nlon) ;
	float graze_sp_doc_zint_100m(time, nlat, nlon) ;
	float graze_sp_zoo_zint_100m(time, nlat, nlon) ;
	float sp_loss_zint_100m(time, nlat, nlon) ;
	float sp_loss_poc_zint_100m(time, nlat, nlon) ;
	float sp_loss_doc_zint_100m(time, nlat, nlon) ;
	float diat_N_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diat_P_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diat_Fe_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diat_SiO3_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diat_light_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float photoC_diat_zint_100m(time, nlat, nlon) ;
	float graze_diat_zint_100m(time, nlat, nlon) ;
	float graze_diat_poc_zint_100m(time, nlat, nlon) ;
	float graze_diat_doc_zint_100m(time, nlat, nlon) ;
	float graze_diat_zoo_zint_100m(time, nlat, nlon) ;
	float diaz_P_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diaz_Fe_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float diaz_light_lim_Cweight_avg_100m(time, nlat, nlon) ;
	float photoC_diaz_zint_100m(time, nlat, nlon) ;
	float graze_diaz_zint_100m(time, nlat, nlon) ;
	float graze_diaz_poc_zint_100m(time, nlat, nlon) ;
	float graze_diaz_doc_zint_100m(time, nlat, nlon) ;
	float graze_diaz_zoo_zint_100m(time, nlat, nlon) ;
	float zoo_loss_zint_100m(time, nlat, nlon) ;
	float zoo_loss_poc_zint_100m(time, nlat, nlon) ;
	float zoo_loss_doc_zint_100m(time, nlat, nlon) ;
	float CO3(time, z_t, nlat, nlon) ;
	float HCO3(time, z_t, nlat, nlon) ;
	float H2CO3(time, z_t, nlat, nlon) ;
	float pH_3D(time, z_t, nlat, nlon) ;
	float co3_sat_calc(time, z_t, nlat, nlon) ;
	float co3_sat_arag(time, z_t, nlat, nlon) ;
	float NITRIF(time, z_t, nlat, nlon) ;
	float DENITRIF(time, z_t, nlat, nlon) ;
	float O2_PRODUCTION(time, z_t, nlat, nlon) ;
	float O2_CONSUMPTION(time, z_t, nlat, nlon) ;
	float AOU(time, z_t, nlat, nlon) ;
	float PAR_avg(time, z_t_150m, nlat, nlon) ;
	float photoC_TOT(time, z_t_150m, nlat, nlon) ;
	float POC_FLUX_100m(time, nlat, nlon) ;
	float POP_FLUX_100m(time, nlat, nlon) ;
	float CaCO3_FLUX_100m(time, nlat, nlon) ;
	float POC_PROD_zint_100m(time, nlat, nlon) ;
	float POC_REMIN_DOCr_zint_100m(time, nlat, nlon) ;
	float POC_REMIN_DIC_zint_100m(time, nlat, nlon) ;
	float CaCO3_PROD_zint_100m(time, nlat, nlon) ;
	float CaCO3_REMIN_zint_100m(time, nlat, nlon) ;
	float POC_FLUX_IN(time, z_t, nlat, nlon) ;
	float POC_PROD(time, z_t, nlat, nlon) ;
	float SiO2_FLUX_IN(time, z_t, nlat, nlon) ;
	float SiO2_PROD(time, z_t, nlat, nlon) ;
	float diaz_Nfix(time, z_t_150m, nlat, nlon) ;
	float ECOSYS_IFRAC(time, nlat, nlon) ;
	float ECOSYS_XKW(time, nlat, nlon) ;
	float ECOSYS_ATM_PRESS(time, nlat, nlon) ;
	float SCHMIDT_O2(time, nlat, nlon) ;
	float O2SAT(time, nlat, nlon) ;
	float CO2STAR(time, nlat, nlon) ;
	float DCO2STAR(time, nlat, nlon) ;
	float pCO2SURF(time, nlat, nlon) ;
	float DpCO2(time, nlat, nlon) ;
	float SCHMIDT_CO2(time, nlat, nlon) ;
	float FG_CO2(time, nlat, nlon) ;
	float PH(time, nlat, nlon) ;
	float ATM_CO2(time, nlat, nlon) ;
	float CO2STAR_ALT_CO2(time, nlat, nlon) ;
	float DCO2STAR_ALT_CO2(time, nlat, nlon) ;
	float DpCO2_ALT_CO2(time, nlat, nlon) ;
	float FG_ALT_CO2(time, nlat, nlon) ;
	float PH_ALT_CO2(time, nlat, nlon) ;
	float ATM_ALT_CO2(time, nlat, nlon) ;
	float IRON_FLUX(time, nlat, nlon) ;
	float CFC_IFRAC(time, nlat, nlon) ;
	float CFC_XKW(time, nlat, nlon) ;
	float CFC_ATM_PRESS(time, nlat, nlon) ;
	float SF6_IFRAC(time, nlat, nlon) ;
	float SF6_XKW(time, nlat, nlon) ;
	float SF6_ATM_PRESS(time, nlat, nlon) ;
	float PO4(time, z_t, nlat, nlon) ;
	float J_PO4(time, z_t, nlat, nlon) ;
	float NO3(time, z_t, nlat, nlon) ;
	float SiO3(time, z_t, nlat, nlon) ;
	float NH4(time, z_t, nlat, nlon) ;
	float Fe(time, z_t, nlat, nlon) ;
	float O2(time, z_t, nlat, nlon) ;
	float Jint_100m_O2(time, nlat, nlon) ;
	float STF_O2(time, nlat, nlon) ;
	float DIC(time, z_t, nlat, nlon) ;
	float J_DIC(time, z_t, nlat, nlon) ;
	float Jint_100m_DIC(time, nlat, nlon) ;
	float FvPER_DIC(time, nlat, nlon) ;
	float FvICE_DIC(time, nlat, nlon) ;
	float DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float J_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float Jint_100m_DIC_ALT_CO2(time, nlat, nlon) ;
	float FvPER_DIC_ALT_CO2(time, nlat, nlon) ;
	float FvICE_DIC_ALT_CO2(time, nlat, nlon) ;
	float ALK(time, z_t, nlat, nlon) ;
	float ALK_ALT_CO2(time, z_t, nlat, nlon) ;
	float Jint_100m_ALK_ALT_CO2(time, nlat, nlon) ;
	float STF_ALK_ALT_CO2(time, nlat, nlon) ;
	float FvPER_ALK_ALT_CO2(time, nlat, nlon) ;
	float FvICE_ALK_ALT_CO2(time, nlat, nlon) ;
	float DOC(time, z_t, nlat, nlon) ;
	float spC_zint_100m_2(time, nlat, nlon) ;
	float spFe(time, z_t_150m, nlat, nlon) ;
	float spCaCO3(time, z_t_150m, nlat, nlon) ;
	float diatChl(time, z_t_150m, nlat, nlon) ;
	float diatC(time, z_t_150m, nlat, nlon) ;
	float diatC_zint_100m_2(time, nlat, nlon) ;
	float diatP(time, z_t_150m, nlat, nlon) ;
	float diatFe(time, z_t_150m, nlat, nlon) ;
	float diatSi(time, z_t_150m, nlat, nlon) ;
	float diazChl(time, z_t_150m, nlat, nlon) ;
	float diazC(time, z_t_150m, nlat, nlon) ;
	float diazC_zint_100m_2(time, nlat, nlon) ;
	float diazP(time, z_t_150m, nlat, nlon) ;
	float diazFe(time, z_t_150m, nlat, nlon) ;
	float CFC11(time, z_t, nlat, nlon) ;
	float STF_CFC11(time, nlat, nlon) ;
	float CFC12(time, z_t, nlat, nlon) ;
	float STF_CFC12(time, nlat, nlon) ;
	float SF6(time, z_t, nlat, nlon) ;
	float STF_SF6(time, nlat, nlon) ;
	float IAGE(time, z_t, nlat, nlon) ;
	float TEND_TEMP(time, z_t, nlat, nlon) ;
	float TEND_SALT(time, z_t, nlat, nlon) ;
	float tend_zint_100m_PO4(time, nlat, nlon) ;
	float tend_zint_100m_NO3(time, nlat, nlon) ;
	float tend_zint_100m_SiO3(time, nlat, nlon) ;
	float tend_zint_100m_NH4(time, nlat, nlon) ;
	float tend_zint_100m_Fe(time, nlat, nlon) ;
	float tend_zint_100m_O2(time, nlat, nlon) ;
	float tend_zint_100m_DIC(time, nlat, nlon) ;
	float tend_zint_100m_DIC_ALT_CO2(time, nlat, nlon) ;
	float tend_zint_100m_ALK(time, nlat, nlon) ;
	float tend_zint_100m_ALK_ALT_CO2(time, nlat, nlon) ;
	float tend_zint_100m_DOC(time, nlat, nlon) ;
	float tend_zint_100m_DOCr(time, nlat, nlon) ;
	float TIDAL_DIFF(time, z_w_bot, nlat, nlon) ;
	float QSW_HBL(time, nlat, nlon) ;
	float KPP_SRC_DIC(time, z_t, nlat, nlon) ;
	float KPP_SRC_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float VDC_T(time, z_w_bot, nlat, nlon) ;
	float VDC_S(time, z_w_bot, nlat, nlon) ;
	float VVC(time, z_w_bot, nlat, nlon) ;
	float DIA_IMPVF_TEMP(time, z_w_bot, nlat, nlon) ;
	float DIA_IMPVF_SALT(time, z_w_bot, nlat, nlon) ;
	float DIA_IMPVF_DIC(time, z_w_bot, nlat, nlon) ;
	float DIA_IMPVF_DIC_ALT_CO2(time, z_w_bot, nlat, nlon) ;
	float DIA_DEPTH(time, nlat, nlon) ;
	float TLT(time, nlat, nlon) ;
	float INT_DEPTH(time, nlat, nlon) ;
	float UISOP(time, z_t, nlat, nlon) ;
	float VISOP(time, z_t, nlat, nlon) ;
	float WISOP(time, z_w_top, nlat, nlon) ;
	float ADVT_ISOP(time, nlat, nlon) ;
	float ADVS_ISOP(time, nlat, nlon) ;
	float VNT_ISOP(time, z_t, nlat, nlon) ;
	float VNS_ISOP(time, z_t, nlat, nlon) ;
	float ISOP_ADV_TEND_TEMP(time, z_t, nlat, nlon) ;
	float Redi_TEND_TEMP(time, z_t, nlat, nlon) ;
	float ISOP_ADV_TEND_SALT(time, z_t, nlat, nlon) ;
	float Redi_TEND_SALT(time, z_t, nlat, nlon) ;
	float USUBM(time, z_t, nlat, nlon) ;
	float VSUBM(time, z_t, nlat, nlon) ;
	float WSUBM(time, z_w_top, nlat, nlon) ;
	float HLS_SUBM(time, nlat, nlon) ;
	float ADVT_SUBM(time, nlat, nlon) ;
	float ADVS_SUBM(time, nlat, nlon) ;
	float VNT_SUBM(time, z_t, nlat, nlon) ;
	float VNS_SUBM(time, z_t, nlat, nlon) ;
	float SUBM_ADV_TEND_TEMP(time, z_t, nlat, nlon) ;
	float SUBM_ADV_TEND_SALT(time, z_t, nlat, nlon) ;
	float HDIFT(time, nlat, nlon) ;
	float HDIFS(time, nlat, nlon) ;
	float HDIFE_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float HDIFN_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float HDIFB_DIC_ALT_CO2(time, z_w_bot, nlat, nlon) ;
	float WVEL(time, z_w_top, nlat, nlon) ;
	float UET(time, z_t, nlat, nlon) ;
	float VNT(time, z_t, nlat, nlon) ;
	float WTT(time, z_w_top, nlat, nlon) ;
	float UES(time, z_t, nlat, nlon) ;
	float VNS(time, z_t, nlat, nlon) ;
	float WTS(time, z_w_top, nlat, nlon) ;
	float ADVT(time, nlat, nlon) ;
	float ADVS(time, nlat, nlon) ;
	float UE_DIC(time, z_t, nlat, nlon) ;
	float VN_DIC(time, z_t, nlat, nlon) ;
	float WT_DIC(time, z_w_top, nlat, nlon) ;
	float UE_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float VN_DIC_ALT_CO2(time, z_t, nlat, nlon) ;
	float WT_DIC_ALT_CO2(time, z_w_top, nlat, nlon) ;
	float Q(time, z_t, nlat, nlon) ;
	float PD(time, z_t, nlat, nlon) ;
	float QSW_HTP(time, nlat, nlon) ;
	float QSW_3D(time, z_w_top, nlat, nlon) ;
	float QFLUX(time, nlat, nlon) ;
	float HMXL(time, nlat, nlon) ;
	float HMXL_DR(time, nlat, nlon) ;
	float XMXL(time, nlat, nlon) ;
	float XMXL_DR(time, nlat, nlon) ;
	float TMXL(time, nlat, nlon) ;
	float TMXL_DR(time, nlat, nlon) ;
	float HBLT(time, nlat, nlon) ;
	float XBLT(time, nlat, nlon) ;
	float TBLT(time, nlat, nlon) ;
	float BSF(time, nlat, nlon) ;
	float MOC(time, transport_reg, moc_comp, moc_z, lat_aux_grid) ;
	float N_HEAT(time, transport_reg, transport_comp, lat_aux_grid) ;
	float N_SALT(time, transport_reg, transport_comp, lat_aux_grid) ;
