#!/bin/bash

#PBS -N tSP
#PBS -q regular
#PBS -l select=32:ncpus=4:mpiprocs=4
#PBS -l walltime=12:00:00
#PBS -A CESM0020

CASE=b.e21.BSMYLE.f09_g17.TBI-ATL_10d50m-anom.1981-02.003

source /etc/profile.d/modules.sh

export MPI_UNBUFFERED_STDIO=true
export TMPDIR=$TMPDIR


##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########

if [ ! -e /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin ]; then
    echo "*************************************************************************************"
    echo "CESM timeseries exiting due to non-existant python virtual environment in"
    echo "    /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin"
    echo "You must first run:"
    echo "$POSTPROCESS_PATH/create_python_env -machine [machine]"
    echo "*************************************************************************************"
    exit
fi

module purge

## activate the virtualenv that contains all the non-bootstrapped dependencies

cd /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin
echo "Running from virtualenv directory:"
pwd
. activate

## load the boot-strap modules 


module load intel/17.0.1
module load ncarenv
module load ncarcompilers
module load mpt/2.19
module load netcdf/4.6.1
module load nco/4.7.4
module load ncl/6.4.0

CASEROOT=/glade/scratch/nanr/post-proc/
today="$(date '+%Y%m%d-%H%M%S')"
log_filename=$CASEROOT/$CASE/postprocess/logs/timeseries.log.$today

mpiexec_mpt dplace -s 1 ./cesm_tseries_generator.py --debug 0  --caseroot ${CASEROOT}/${CASE}/postprocess >> ${log_filename} 2>&1

