#! /usr/bin/env bash
##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########

#!/bin/bash

#PBS -N xconform
#PBS -q regular
#PBS -l select=16:ncpus=4:mpiprocs=4
#PBS -l walltime=12:00:00
#PBS -A UESM0006

source /etc/profile.d/modules.sh

export MPI_UNBUFFERED_STDIO=true
export TMPDIR=$TMPDIR


if [ ! -e /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin ]; then
    echo "*************************************************************************************"
    echo "CESM xconform exiting due to non-existant python virtual environment in"
    echo "    /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin"
    echo "You must first run:"
    echo "$SRCROOT/postprocessing/create_python_env -machine [machine]"
    echo "*************************************************************************************"
    exit
fi


module purge


source /glade/u/home/mickelso/CESM_postprocessing_3//cesm-env2/bin/activate


module load intel/17.0.1

module load ncarenv

module load ncarcompilers

module load mpt/2.19

module load netcdf/4.6.1

module load nco/4.7.4

module load ncl/6.4.0




today="$(date '+%Y%m%d-%H%M%S')"

mpiexec_mpt dplace -s 1 cesm_conform_generator.py --debug 0  --caseroot /glade/work/nanr/CESM2-covid/b.e21.BSSP245cmip6.f09_g17.COVID-cvd.101/postprocess >> /glade/work/nanr/CESM2-covid/b.e21.BSSP245cmip6.f09_g17.COVID-cvd.101/postprocess/logs/xconform.log.$today 2>&1

